# Generated by Django 5.0.3 on 2024-03-19 14:03

import django.core.validators
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_videoemb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="videoemb",
            field=models.FileField(
                upload_to=videos.models.uploadPath,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mov", "mp4", "avi", "wmv"]
                    )
                ],
            ),
        ),
    ]
