# Generated by Django 5.0.3 on 2024-03-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_video_videoemb"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(default=False, editable=False, upload_to=""),
        ),
    ]
