# Generated by Django 5.0.3 on 2024-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                default="image/image.png", editable=False, upload_to=""
            ),
        ),
    ]
