# Generated by Django 5.0.3 on 2024-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_alter_video_videoemb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                default="image/image.png", editable=False, max_length=255, upload_to=""
            ),
        ),
    ]
