# Generated by Django 5.0.3 on 2024-04-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_alter_video_description_alter_video_videoemb"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-created_at"]},
        ),
    ]
