# Generated by Django 5.0.3 on 2024-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customusers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
