# Generated by Django 5.0.3 on 2024-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customusers", "0005_alter_customuser_vertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscriberstotal",
            field=models.BigIntegerField(default=0),
        ),
    ]
