# Generated by Django 5.0.3 on 2024-04-07 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pinnedvideos", "0002_pinnedvideo_author"),
        ("videos", "0012_alter_video_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pinnedvideo",
            constraint=models.CheckConstraint(
                check=models.Q(("pinning_user", models.F("author"))),
                name="user_and_video_author_same",
            ),
        ),
    ]
